language: ruby
rvm:
- 2.3.0
install:
- bundle config --local path .bundle/gems
- bundle config --local without coverage docs
- bundle --jobs 3 --retry 3
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: vmfvLpVp5ke2ANo5rzt76t6pizi723fnF+VMLsRoRKqXqpWtPvOeGhgocNi9SUvOjUckniZ/B0289Y+ZUV4lDBDigS0FkbVkmKjytEU7idnw2VbUe2567LIRgBZ5F6/T0FEKyWidsKA4qzvOpM428jcFqqn78S3VURv4nZznl4WTI0/2KNgKPtJt7mL9St/6LhtckBe7kCwvVKYBIvaiVvx+oK/1avHIEwb7rTTAMcL+z4r09evVK8uMDKIlOLCyU96TAVpES+WYbbDjDF00sUVU08dJ90VbvS1kKTZKOIbq3HjgY39uPyZnXZhlenwfHQY8aMLG0jgmYHgQgsB0BothrA+9Ld7BeGt4qvIY9UiTsm3m3Ndi1TaodKKZw/i5f20pXgajy+Y6xcV8B5UJx3NqcplbNQzUQwqHl/l7f86G059jpXOyFzYDCAd0/UZy5TSXo1RQ4UwiSUtUpXKXR/KOLAOIXlsiYGCaD8hYRoXvC6uY20OYiCLlDrsGwnI2yyJCMs4uSF34P5TaDqkimb4SPEPLFT9uYxSsUKfi9SB5CjgHj2qVS0aMKqCyvFxj3dhjHyWMe20NhM1BigfFx0cSnIAjvxQi6Mq9GQQq7NVayqoXL7fmqMkRI6Tjg2i7bu4AibPyKiP+UZKc8n+VJd4YVsOS6uG2SAfslIzVWOA=
