language: ruby
rvm:
- 2.2.0
install:
- bundle config --local path .bundle/gems
- bundle config --local without coverage docs
- bundle --jobs 3 --retry 3
script: bundle exec rake deploy
env:
  global:
    secure: Tu1QdIx3dzVwrR7y/kWA2hJHjYZsCWKQRY6H6CsJNUX2v8anoTjplxaR9eaRqpiJKqUHEfdfMORQmM7zjToTBzMfzAtfn+IdKWVCXeSTz7fQWoFfq/1HUeJ5E+hzaZ0zsfrQduAeMnmdj0koTeZgpSXjEe35yohXTv8EC66BLZNVGHYpjjLwqkoY3H6K1y5nnNxMagjypfNW0/CNfPuJFMZMYgkVH8lKeFZ0ZCkqtH+9CZvWZoZo8WZnieTcbRNnEfS4uYhNIJhI3rN+mZmwHOouStwhAUl8o02RetAy0Sk7DaBDcxYA+AHlYMcpD7egfli5m0rezHuu1D/9U5t4o90xWJ9Hw2CQ/+wz8I7djZjl5WPgjp9bD5N8wuLyvUufwJ51hJbw7y3b+qZ8d2H4TY9ykQw47EVPMDNffEDVgbcA5BV3GCCa2rlxOoJ4pIQcz1DXRrOfCF4iEaYucy05LMpAuhKESySJQvPG7QlGML4pXtIPiL4I6Rw07SQfVyBD2ZNytfp0z4ZgINTqywTsqtClitU638denoA4m5EYQPZP0i/EPsn7oGLOjRVqn7Blt+MsYQqRMf5biEycU1KnLZdNhZv0xBOeGztkzyl5yJLtlc9mE/VMT3KpdbJBhgWsq/41YsFfYOurS4FtZxOKvsm8HFERNcWlYdZk3JpC2eI=
